export const SEARCH_MOVIE = 'movie-app/SEARCH_MOVIE';
export const SEARCH_MOVIE_REQUEST = 'movie-app/SEARCH_MOVIE_REQUEST';
export const SEARCH_MOVIE_SUCCESS = 'movie-app/SEARCH_MOVIE_SUCCESS';
export const SEARCH_MOVIE_ERROR = 'movie-app/SEARCH_MOVIE_ERROR';

export const ADD_MOVIE_TO_FAVORITES = 'movie-app/ADD_MOVIE_TO_FAVORITES';
export const ADD_MOVIE_TO_FAVORITES_REQUEST = 'movie-app/ADD_MOVIE_TO_FAVORITES_REQUEST';
export const ADD_MOVIE_TO_FAVORITES_SUCCESS = 'movie-app/ADD_MOVIE_TO_FAVORITES_SUCCESS';
export const ADD_MOVIE_TO_FAVORITES_ERROR = 'movie-app/ADD_MOVIE_TO_FAVORITES_ERROR';

export const REMOVE_MOVIE_FROM_FAVORITES = 'movie-app/REMOVE_MOVIE_FROM_FAVORITES';
export const REMOVE_MOVIE_FROM_FAVORITES_REQUEST = 'movie-app/REMOVE_MOVIE_FROM_FAVORITES_REQUEST';
export const REMOVE_MOVIE_FROM_FAVORITES_SUCCESS = 'movie-app/REMOVE_MOVIE_FROM_FAVORITES_SUCCESS';
export const REMOVE_MOVIE_FROM_FAVORITES_ERROR = 'movie-app/REMOVE_MOVIE_FROM_FAVORITES_ERROR';
