export const SEARCH_MOVIE = 'movie-app/SEARCH_MOVIE';
export const SEARCH_MOVIE_REQUEST = 'movie-app/SEARCH_MOVIE_REQUEST';
export const SEARCH_MOVIE_SUCCESS = 'movie-app/SEARCH_MOVIE_SUCCESS';
export const SEARCH_MOVIE_ERROR = 'movie-app/SEARCH_MOVIE_ERROR';

export const ADD_MOVIE_TO_FAVORITES = 'movie-app/ADD_MOVIE_TO_FAVORITES';

export const REMOVE_MOVIE_FROM_FAVORITES = 'movie-app/REMOVE_MOVIE_FROM_FAVORITES';

export const FETCH_MOVIE_TRAILER = 'movie-app/FETCH_MOVIE_TRAILER';
export const FETCH_MOVIE_TRAILER_REQUEST = 'movie-app/FETCH_MOVIE_TRAILER_REQUEST';
export const FETCH_MOVIE_TRAILER_SUCCESS = 'movie-app/FETCH_MOVIE_TRAILER_SUCCESS';
export const FETCH_MOVIE_TRAILER_ERROR = 'movie-app/FETCH_MOVIE_TRAILER_ERROR';

export const RESET_MOVIE_TRAILERS = 'movie-app/RESET_MOVIE_TRAILERS';
